export const schemaStatements: string[] = [
  "-- Additive assistant knowledge overlays, retrieval cache and review inbox.\nCREATE EXTENSION IF NOT EXISTS vector",
  "CREATE TABLE IF NOT EXISTS assistant_documents (\n id text PRIMARY KEY, title text NOT NULL, content text NOT NULL, source_url text NOT NULL,\n replaces text[] NOT NULL DEFAULT '{}', status text NOT NULL CHECK(status IN ('published','retired')),\n revision integer NOT NULL DEFAULT 1, updated_at timestamptz NOT NULL DEFAULT now()\n)",
  "CREATE TABLE IF NOT EXISTS assistant_document_chunks (\n id text PRIMARY KEY, document_id text NOT NULL REFERENCES assistant_documents(id),\n content text NOT NULL, embedding vector(768) NOT NULL, embedding_model text NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS assistant_retrieval_cache (\n key text PRIMARY KEY, revision text NOT NULL, value jsonb NOT NULL, expires_at timestamptz NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS assistant_feedback (\n id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, fingerprint text UNIQUE NOT NULL,\n question text NOT NULL, answer text NOT NULL DEFAULT '', reason text NOT NULL, sources jsonb NOT NULL DEFAULT '[]',\n status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved')),\n occurrences integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()\n)",
  "CREATE INDEX IF NOT EXISTS assistant_feedback_status ON assistant_feedback(status,updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS assistant_cache_expiration ON assistant_retrieval_cache(expires_at)",
  "CREATE OR REPLACE FUNCTION assistant_publish_document(payload jsonb, expected_revision integer)\nRETURNS integer LANGUAGE plpgsql AS $$\nDECLARE current_revision integer; next_revision integer; item jsonb; doc_id text;\nBEGIN\n doc_id:=payload->>'id';\n PERFORM pg_advisory_xact_lock(hashtextextended('assistant-document:'||doc_id,0));\n SELECT revision INTO current_revision FROM assistant_documents WHERE id=doc_id FOR UPDATE;\n IF COALESCE(current_revision,0) <> expected_revision THEN\n  RAISE EXCEPTION 'Document changed; reload before publishing' USING ERRCODE='40001';\n END IF;\n next_revision:=COALESCE(current_revision,0)+1;\n INSERT INTO assistant_documents(id,title,content,source_url,replaces,status,revision)\n VALUES(doc_id,payload->>'title',payload->>'content',payload->>'sourceUrl',\n  ARRAY(SELECT jsonb_array_elements_text(payload->'replaces')),payload->>'status',next_revision)\n ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,content=EXCLUDED.content,source_url=EXCLUDED.source_url,\n  replaces=EXCLUDED.replaces,status=EXCLUDED.status,revision=next_revision,updated_at=now();\n DELETE FROM assistant_document_chunks WHERE document_id=doc_id;\n IF payload->>'status'='published' THEN\n  FOR item IN SELECT value FROM jsonb_array_elements(payload->'chunks') LOOP\n   INSERT INTO assistant_document_chunks VALUES(doc_id||':'||(item->>'index'),doc_id,item->>'content',\n    (item->>'embedding')::vector,'icdu-embed-v1');\n  END LOOP;\n END IF;\n DELETE FROM assistant_retrieval_cache;\n RETURN next_revision;\nEND;\n$$;\n"
];
